baseurl = "http://daqian.gift/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-us"
title = "Daqian"
theme = "hyde"
canonifyurls = true

[params]
    description = "这里是曾大千的个人博客"
    themeColor = "theme-base-08" # for hyde theme